site_title: Boris Smus
date_format: '%d %B %Y'
permalink_format:
  post: '{{year}}/{{slug}}'
  link: '{{year}}/{{slug}}'
  page: '{{slug}}'
  draft: 'drafts/{{slug}}'
  archive: 'archive/{{slug}}'
  index: ''
